[project]
name = "src"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "boto3>=1.37.38",
    "fastapi[standard]>=0.115.12",
    "scikit-learn>=1.3.2",
    "xgboost>=2.1.4",
]
